### ISSUE TITLE
getAppSettings not defined

### ISSUE THREAD

**Issue by alexormrod** [nprutan/koa-shopify-auth-cookieless#1]
You reference a method getAppSettings here. But it is not defined/imported anywhere. 

Ty!

**Comment by nprutan** [comment]
Hi @alexormrod, thanks for raising this issue. Sorry, it's taken so long to respond. 

This function is not part of the package. It's being used to store credentials in AWS AppSync.

If you'd like to see what that looks like here it is:

```
const getAppSettings = async (shop) => {
  const shopHash = generateShopHash(shop);

  return await API.graphql(
    graphqlOperation(getUser, {
      id: shopHash,
    })
  );

function generateShopHash(shop) {
  return shajs("sha256").update(shop).digest("hex");
}
```

I'm simply hashing the shopOrigin when first interacting with a Shopify store and using this as a key for retrieving settings from AppSync. 

Here's an example GQL query for (some) of the fields that I'm storing in AppSync:

```
const getUser = `
  query GetUser($id: ID!) {
    getUser(id: $id) {
      id
      shopOrigin
      token
      appActive
      ownerEmail
    }
  }
`;
};
```

Hope that helps clear up where that function is defined. I think I mentioned this in the code snippet on the repo, but I probably should have been more clear.

Let me know if you have any further questions!
